# Configuration for dev

version: '3.4'

services:
    apn-app:
        restart: always
        build:
            context: ./apn-app/
            dockerfile: docker/python/Dockerfile
        volumes:
            - ./apn-app/:/srv/www/apn-app
        links:
          - apn-postgres:apn-postgres
        expose:
          - 8000
        ports:
            - 8000:8000
        env_file:
            - .env
        depends_on:
            - apn-postgres
        stdin_open: true
        tty: true

    apn-postgres:
        image: postgres:13-alpine
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: "${POSTGRES_DB}"
            POSTGRES_USER: "${POSTGRES_USER}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./apn-app/logs:/srv/www/apn-app/logs

    apn-ui:
        build:
          context: ./apn-ui
          dockerfile: docker/vuejs/Dockerfile
          target: 'develop-stage'
        ports:
        - '8080:8080'
        env_file:
              - .env
        volumes:
        - ./apn-ui/:/app
        command: /bin/sh -c "yarn serve"


volumes:
    pgdata:



