# Configuration for dev

version: '3'

services:
    apn-app:
        restart: always
        build:
            context: ./apn-app/
            dockerfile: docker/python/Dockerfile
        volumes:
            - ./apn-app/:/srv/www/apn-app
        links:
          - apn-postgres:apn-postgres
        expose:
          - 8000
        ports:
            - 8000:8000
        env_file:
            - .dev.env
        depends_on:
            - apn-postgres
        stdin_open: true
        tty: true

    apn-postgres:
        image: postgres:13-alpine
        restart: always
#        env_file:
#            - .dev.env
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: "${POSTGRES_DB}"
            POSTGRES_USER: "${POSTGRES_USER}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./logs:/srv/www/property-project/logs

    apn-ui:
        restart: always
        build:
            context: ./apn-ui
            dockerfile: docker/vuejs/Dockerfile
        volumes:
            - ./apn-ui/:/srv/www/code
        expose:
            - 8080
        ports:
            - 8080:8080
            - 8081:8081
        stdin_open: true
        tty: true
        environment:
            - CHOKIDAR_USEPOLLING=true


volumes:
    pgdata:



