# Generated by Django 3.0.4 on 2021-08-05 14:02

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrative_dist_ru', models.CharField(max_length=150)),
                ('administrative_dist_ukr', models.CharField(max_length=150)),
                ('administrative_old_dist_ru', models.CharField(blank=True, max_length=150, null=True)),
                ('administrative_old_dist_urk', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Административный район',
                'verbose_name_plural': 'Административные районы',
            },
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer_name', models.CharField(max_length=150, unique=True, verbose_name='Название застройщика')),
            ],
            options={
                'verbose_name': 'Застройщик',
                'verbose_name_plural': 'Застройщики',
            },
        ),
        migrations.CreateModel(
            name='FlatForSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.PositiveSmallIntegerField(default=1, verbose_name='Кол-во комнат')),
                ('total_area', models.FloatField(default=1, verbose_name='Общая площадь')),
                ('living_area', models.FloatField(default=1, verbose_name='Жилая площадь')),
                ('kitchen_area', models.FloatField(default=1, verbose_name='Кухонная площадь')),
                ('floor', models.SmallIntegerField(default=1, verbose_name='Этаж')),
                ('price', models.IntegerField(default=1, verbose_name='Цена')),
                ('description', models.CharField(default=1, max_length=500, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Новострой в продаже',
                'verbose_name_plural': 'Новострои в продаже',
            },
        ),
        migrations.CreateModel(
            name='NewBuilding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=1, max_length=200, verbose_name='Название')),
                ('house_number', models.CharField(max_length=10, verbose_name='Номер дома')),
                ('house_letter', models.CharField(blank=True, choices=[('', 'Без бувы'), ('А', 'А'), ('Б', 'Б'), ('В', 'В'), ('Г', 'Г'), ('Д', 'Д'), ('Е', 'Е'), ('Ё', 'Ё'), ('Ж', 'Ж'), ('З', 'З'), ('И', 'И'), ('Й', 'Й'), ('К', 'К'), ('Л', 'Л'), ('М', 'М'), ('Н', 'Н'), ('О', 'О'), ('П', 'П'), ('Р', 'Р'), ('С', 'С'), ('Т', 'Т'), ('У', 'У'), ('Ф', 'Ф'), ('Х', 'Х'), ('Ц', 'Ц'), ('Ч', 'Ч'), ('Ш', 'Ш'), ('Щ', 'Щ'), ('Ъ', 'Ъ'), ('Ы', 'Ы'), ('Ь', 'Ь'), ('Э', 'Э'), ('Ю', 'Ю'), ('Я', 'Я')], max_length=2, null=True, verbose_name='Буква дома')),
                ('district', models.CharField(choices=[('', 'Не заполнено'), ('Центр', (('ce', 'Центр'), ('gos', 'Госпром'), ('nag', 'Нагорный'), ('sog', 'Сосновая горка'), ('sok', 'Сокольники'), ('sha', 'Шатиловка'), ('nam', 'Научная метро'), ('nic', 'Нижний центр'), ('pcm', 'Площадь Конституции метро'), ('pum', 'Пушкинская метро'))), ('Прилегающие к центру', (('ujd', 'ЮЖД'), ('cer', 'Центральный рынок'))), ('Гагарина (Левада)', (('gam', 'Спортивная метро'), ('spm', 'Спортивная метро'), ('noc', 'Новый цирк'), ('kor', 'Конный рынок'), ('zum', 'Защитников Украины метро'))), ('Одесская районы', (('ode', 'Одесская'), ('osn', 'Основа'), ('aer', 'Аэропорт'), ('arp', 'Артема парк'), ('zmm', 'Завод Малышева метро'), ('ujn', 'Южнопроэктная'))), ('Холодногорское направление', (('hog', 'Холодная гора'), ('lig', 'Лысая гора'), ('zal', 'Залютино'), ('bav', 'Бавария'), ('nov', 'Новоселовека'), ('pes', 'Песочин'))), ('Новожановское направление', (('nov', 'Новожаново'), ('zam', 'Завод Шевченко'), ('mos', 'Москалевка'))), ('Роганское направление', (('htz', 'ХТЗ'), ('inm', 'Индустриальная метро'), ('htm', 'ХТЗ метро'), ('vop', 'Восточный поселок'), ('rog', 'Рогань'), ('gor', 'Горизонт'), ('sol', 'Солнечный'), ('nop', 'Новозападный поселок'))), ('Пятихатское направление', (('jup', 'Жуковского поселок'), ('les', 'Лесопарк'), ('pya', 'Пятихатки'))), ('Салтовское направление', (('sal', 'Салтовка'), ('ses', 'Северная Салтовка'), ('sts', 'Старая Салтовка'), ('sad', 'Сабурова Дача'), ('frb', 'Французский Бульвар'), ('kip', 'Кирова поселок'), ('kul', 'Кулиничи'), ('tur', 'Тюринка'), ('bod', 'Большая Даниловка'), ('nem', 'Немышля'), ('jur', 'Журавлевка'), ('kim', 'Киевская метро'), ('shi', 'Шишковка'), ('mjk', 'МЖК'))), ('Алексеевское направление', (('ale', 'Алексеевка'), ('pap', 'Павловое Поле'), ('pav', 'Павловка'), ('sor', 'Сортировка'), ('iva', 'Ивановка'))), ('Новые Дома', (('nod', 'Новые Дома'), ('kor', 'Коммунальный Рынок'), ('dvs', 'Дворец Спорта'), ('22b', '22 Больница'), ('mam', 'Масельского метро'), ('arm', 'Армейская метро'), ('mpm', 'Московский Проспект метро')))], max_length=4, verbose_name='Район')),
                ('micro_district', models.CharField(blank=True, choices=[('dne', 'Не делится на микрорайоны'), ('', 'Не заполнено'), ('601', '601'), ('602', '602'), ('603', '603'), ('604', '604'), ('605', '605'), ('606', '606'), ('606a', '606-A'), ('607', '607'), ('608', '608'), ('615', '615'), ('616', '616'), ('624', '624'), ('625', '625'), ('626', '626'), ('656', '656'), ('520', '520'), ('522', '522'), ('524', '524'), ('531', '531'), ('533', '533'), ('535', '535'), ('hl8', '8 Хлебзавод'), ('ss1', 'Северная Салтовка - 1'), ('ss2', 'Северная Салтовка - 2'), ('ss3', 'Северная Салтовка - 3'), ('ss4', 'Северная Салтовка - 4'), ('ss5', 'Северная Салтовка - 5')], default='', max_length=4, null=True, verbose_name='Микрорайон')),
                ('houising_number', models.CharField(blank=True, choices=[('', 'Не делится на корпуса'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='', max_length=2, null=True, verbose_name='Номер корпуса')),
                ('location', models.CharField(blank=True, default=1, max_length=200, null=True, verbose_name='Расположение')),
                ('the_class', models.CharField(blank=True, choices=[('', 'Не заполнено'), ('ec', 'Эконом'), ('co', 'Комфорт'), ('bu', 'Бизнес'), ('pr', 'Премиум'), ('el', 'Элит'), ('de', 'Делюкс'), ('to', 'Townhouse')], default='', max_length=2, null=True, verbose_name='Класс')),
                ('number_of_storeys', models.PositiveSmallIntegerField(default=1, verbose_name='Этажность')),
                ('number_of_buildings', models.PositiveSmallIntegerField(default=1, verbose_name='Количество домов')),
                ('number_of_sections_or_entrances', models.IntegerField(default=1, verbose_name='Количество секций/подьездов')),
                ('construction_technology', models.CharField(blank=True, choices=[('', 'Не заполнено'), ('br', 'Кирпичная кладка'), ('mf', 'Монолитно-каркасная'), ('pa', 'Панельная')], default='', max_length=2, null=True, verbose_name='Технология строительства')),
                ('walls_type', models.CharField(blank=True, choices=[('', 'Не заполнено'), ('br', 'Кирпич'), ('gb', 'Газоблок'), ('pb', 'Керамоблок')], default='', max_length=2, null=True, verbose_name='Стены')),
                ('warming', models.CharField(blank=True, choices=[('', 'Не заполнено'), ('st', 'Пенопласт'), ('ep', 'Пенополистирол'), ('mw', 'Минеральная вата'), ('ot', 'Другое')], default='', max_length=2, null=True, verbose_name='Утепление')),
                ('room_height', models.FloatField(default=1, verbose_name='Высота помещений')),
                ('number_of_apartments_in_house', models.PositiveSmallIntegerField(default=1, verbose_name='Кол-во квартир в доме')),
                ('number_of_one_room', models.PositiveSmallIntegerField(default=1, verbose_name='Кол-во 1к.кв.')),
                ('square_of_one_room', models.FloatField(default=1, verbose_name='Площадь 1к.кв.')),
                ('number_of_two_room', models.PositiveSmallIntegerField(default=1, verbose_name='Кол-во 2к.кв.')),
                ('square_of_two_room', models.FloatField(default=1, verbose_name='Площадь 2к.кв.')),
                ('number_of_three_room', models.PositiveSmallIntegerField(default=1, verbose_name='Кол-во 3к.кв.')),
                ('square_of_three_room', models.FloatField(default=1, verbose_name='Площадь 3к.кв.')),
                ('number_of_four_room', models.PositiveSmallIntegerField(default=1, verbose_name='Кол-во 4к.кв.')),
                ('square_of_four_room', models.FloatField(default=1, verbose_name='Площадь 4к.кв.')),
                ('number_of_apartments_per_floor', models.PositiveSmallIntegerField(default=1, verbose_name='Кол-во квартир на этаже')),
                ('commercial_premises', models.PositiveSmallIntegerField(default=1, null=True, verbose_name='Коммерческие помещения')),
                ('heating', models.CharField(blank=True, choices=[('', 'Не заполнено'), ('ce', 'Центральное'), ('ag', 'Автономное газовое'), ('ae', 'Автономное электрическое'), ('ah', 'Автономное на дом')], default='', max_length=2, null=True, verbose_name='Отопление')),
                ('gasification', models.BooleanField(default=1, verbose_name='Газификация')),
                ('elevator', models.CharField(default=1, max_length=50, verbose_name='Лифт')),
                ('parking', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('', 'Не заполнено'), ('un', 'Подземный'), ('gr', 'Наземный'), ('gu', 'Гостевой'), ('bk', 'Велопарковки')], default='', max_length=12, null=True, verbose_name='Паркинг')),
                ('number_of_parking_spaces', models.SmallIntegerField(default=1, verbose_name='Кол-во машиномест')),
                ('price', models.SmallIntegerField(default=1, verbose_name='Цена за м2 у застройщика')),
                ('completion_date', models.SmallIntegerField(default=1, verbose_name='Сдан и принят в эксплуатацию')),
                ('description', models.TextField(default=1, verbose_name='Описание')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('lat', models.FloatField(blank=True, default=0, null=True, verbose_name='Широта')),
                ('lng', models.FloatField(blank=True, default=0, null=True, verbose_name='Долгота')),
                ('administrative_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AdministrativeDistrict', verbose_name='Административный район')),
                ('developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Developer', verbose_name='Застройщик')),
            ],
            options={
                'verbose_name': 'Новострой',
                'verbose_name_plural': 'Новострои',
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_ru', models.CharField(max_length=150, verbose_name='Улица на русском')),
                ('street_uk', models.CharField(max_length=150, verbose_name='Улица на украинском')),
            ],
            options={
                'verbose_name': 'Улица',
                'verbose_name_plural': 'Улицы',
            },
        ),
        migrations.CreateModel(
            name='WayFromMetro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metro', models.CharField(choices=[('', 'Не заполнено'), ('Салтовская линия', (('gtr', 'Героев Труда'), ('stk', 'Студенческая'), ('akp', 'Академика Павлова'), ('akb', 'Академика Барабашова'), ('kie', 'Киевская'), ('psh', 'Пушкинская'), ('uni', 'Университет'), ('ism', 'Исторический Музей'))), ('Алексеевская линия', (('pob', 'Победа'), ('ale', 'Алексеевская'), ('23a', '23 Августа'), ('bts', 'Ботанический сад'), ('nau', 'Научная'), ('gos', 'Госпром'), ('arb', 'Архитектора Бикетова'), ('zau', 'Защитников Украины'), ('met', 'Метростроителей'))), ('Холодногорско-Заводская линия', (('hog', 'Холодная Гора'), ('ujv', 'Южный Вокзал'), ('cer', 'Центральный рынок'), ('plk', 'Площадь Конституции'), ('prg', 'Проспект Гагарина'), ('spo', 'Спортинвая'), ('zim', 'Завод имени Малышева'), ('mop', 'Московский Проспект'), ('dvs', 'Дворец Спорта'), ('arm', 'Армейская'), ('imm', 'Имени А.С. Масельского'), ('trz', 'Тракторный Завод'), ('ind', 'Индустриальная')))], default='', max_length=3, verbose_name='Метро')),
                ('time', models.SmallIntegerField(default=1, verbose_name='Время')),
                ('type_of_movement', models.CharField(choices=[('', 'Не заполнено'), ('of', 'Пешком'), ('bc', 'На машине')], default='', max_length=2, verbose_name='Как')),
                ('number_of_meters', models.SmallIntegerField(default=1, verbose_name='Расстояние')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ways_from_metro', to='api.NewBuilding', to_field='slug')),
            ],
        ),
        migrations.AddField(
            model_name='newbuilding',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='street', to='api.Street', verbose_name='Улица'),
        ),
        migrations.CreateModel(
            name='LayoutImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Планировки')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layout_images', to='api.NewBuilding', to_field='slug')),
            ],
        ),
        migrations.CreateModel(
            name='FlatForSaleLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_layout', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Планировка квартиры')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flat_layouts', to='api.FlatForSale')),
            ],
        ),
        migrations.CreateModel(
            name='FlatForSaleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото квартиры')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flat_images', to='api.FlatForSale')),
            ],
        ),
        migrations.AddField(
            model_name='flatforsale',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flats_for_sale', to='api.NewBuilding', to_field='slug', verbose_name='Дом'),
        ),
        migrations.CreateModel(
            name='BuildingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_images', to='api.NewBuilding', to_field='slug')),
            ],
        ),
    ]
